(()=>{
const App=window.AITradeX,Auth=window.AITradeXAuth,root=document.getElementById("app");let page="overview";
function loginScreen(msg=""){root.innerHTML=`<main class="control-login"><section class="control-card"><div class="brand center"><span>AI</span><b>AITradeX Control</b></div><h1>Control Center</h1><p>Separate access for platform operations.</p>${msg?`<div class="error-box">${msg}</div>`:""}<form onsubmit="AITradeXControl.login(event)" class="form-grid"><label>Email<input id="controlEmail" type="email" required placeholder="control@aitradex.com"/></label><label>Password<input id="controlPassword" type="password" required placeholder="Password"/></label><button class="btn">Open Control Center</button></form><button onclick="location.href='index.html'" class="link-btn">Back to AITradeX</button></section></main>`}
const title=(t,s)=>`<div class="page-title"><div><h1>${t}</h1><p>${s}</p></div></div>`;
const metric=(l,v,s,i)=>`<article class="metric-card"><div class="metric-top"><span>${l}</span><i>${i}</i></div><strong>${v}</strong><small>${s}</small></article>`;
function shell(content){const menu=[["overview","Overview","⌂"],["users","Users","●"],["kyc","KYC","✓"],["payments","Payment Methods","◈"],["deposits","Deposits","₹"],["withdrawals","Withdrawals","↙"],["trades","AI Trades","↗"],["plans","Plans","◆"],["referrals","Referrals","★"],["settings","Settings","⚙"]];root.innerHTML=`<div class="app-shell control-shell"><aside class="sidebar"><div class="brand side-brand"><span>AI</span><b>AITradeX</b></div><nav>${menu.map(([k,l,i])=>`<button class="${page===k?"active":""}" onclick="AITradeXControl.go('${k}')"><i>${i}</i>${l}</button>`).join("")}</nav><button class="logout-btn" onclick="AITradeXControl.logout()">Logout</button></aside><main class="main-area">${content}</main></div>`}
function overview(){const users=App.state.users.filter(u=>u.role==="user").length,kyc=App.state.kycRequests.filter(k=>k.status==="PENDING").length,dep=App.state.depositRequests.filter(d=>d.status==="PENDING").length,wit=App.state.withdrawalRequests.filter(w=>w.status==="PENDING").length;shell(`${title("Control Overview","AITradeX operations summary.")}<section class="metrics-grid">${metric("Users",users,"Registered users","●")}${metric("Pending KYC",kyc,"Need review","✓")}${metric("Pending Deposits",dep,"Need approval","₹")}${metric("Pending Withdrawals",wit,"Need action","↙")}</section><section class="panel-card"><div class="section-head"><h3>Phase 1 Control Center</h3><span>Functional modules will be connected phase-wise.</span></div><p class="info-box">User and control center are fully separate. User panel does not show control wording.</p></section>`)}
function placeholder(n,s){shell(`${title(n,s)}<section class="panel-card"><p class="info-box">${n} module will be connected in upcoming phases without patching old code.</p></section>`)}
function render(){const u=App.currentUser();if(!u||u.role!=="admin")return loginScreen();if(page==="overview")return overview();const map={users:["Users","View and manage platform users."],kyc:["KYC Requests","Approve or reject user verification."],payments:["Payment Methods","Verify KYC-name matched UPI and bank accounts."],deposits:["Deposit Requests","Approve 12 digit UTR deposits."],withdrawals:["Withdrawal Requests","Approve or reject withdrawal requests."],trades:["AI Trades","Close user trades with profit/loss settlement."],plans:["Subscription Plans","Create and manage AI plans."],referrals:["Referral Reports","One-time 10% first deposit commission."],settings:["Settings","Deposit details, limits and platform settings."]};const [n,s]=map[page]||["Control","Module"];placeholder(n,s)}
window.AITradeXControl={login(e){e.preventDefault();try{Auth.loginControl({email:controlEmail.value,password:controlPassword.value});page="overview";App.toast("Control center opened.");render()}catch(err){loginScreen(err.message)}},go(p){page=p;render()},logout(){App.clearSession();loginScreen()}};render();
})();