-- AI Trading Assistant Supabase Schema
-- Supabase Dashboard > SQL Editor > New Query > Paste this full file > Run

create table if not exists public.profiles (
  id text primary key,
  created_at timestamp with time zone default now(),
  name text,
  email text unique,
  mobile text,
  role text default 'user',
  plan text default 'Free',
  referral_code text unique,
  referred_by text
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text references public.profiles(id),
  coin text,
  side text,
  amount numeric,
  entry_price numeric,
  current_price numeric,
  pnl numeric,
  status text default 'RUNNING'
);

create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  plan text,
  name text,
  mobile text,
  txn text,
  screenshot_url text,
  status text default 'PENDING'
);

create table if not exists public.deposit_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  user_email text,
  amount numeric,
  txn text,
  screenshot_url text,
  status text default 'PENDING'
);

create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  user_email text,
  amount numeric,
  method text,
  account text,
  name text,
  ifsc text,
  status text default 'PENDING'
);

create table if not exists public.wallet_ledger (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  type text,
  amount numeric,
  note text
);

create table if not exists public.subscription_plans (
  id text primary key,
  created_at timestamp with time zone default now(),
  name text,
  price numeric default 0,
  duration text,
  signal_limit numeric default 5,
  features jsonb default '[]'::jsonb,
  active boolean default true
);

create table if not exists public.kyc_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  user_email text,
  name text,
  mobile text,
  doc_type text,
  doc_number text,
  front_file text,
  selfie_file text,
  status text default 'PENDING'
);

create table if not exists public.admin_signals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  coin text,
  signal text,
  entry_price numeric,
  target_price numeric,
  stop_loss numeric,
  confidence numeric,
  risk_level text,
  expiry text,
  note text
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  referral_code text,
  joined_user_email text,
  bonus numeric default 50,
  status text default 'JOINED'
);

alter table public.profiles enable row level security;
alter table public.trades enable row level security;
alter table public.payment_requests enable row level security;
alter table public.deposit_requests enable row level security;
alter table public.withdrawal_requests enable row level security;
alter table public.wallet_ledger enable row level security;
alter table public.subscription_plans enable row level security;
alter table public.kyc_requests enable row level security;
alter table public.admin_signals enable row level security;
alter table public.referrals enable row level security;

drop policy if exists "public read profiles" on public.profiles;
drop policy if exists "public insert profiles" on public.profiles;
drop policy if exists "public update profiles" on public.profiles;

drop policy if exists "public read trades" on public.trades;
drop policy if exists "public insert trades" on public.trades;

drop policy if exists "public read payments" on public.payment_requests;
drop policy if exists "public insert payments" on public.payment_requests;
drop policy if exists "public update payments" on public.payment_requests;

drop policy if exists "public read deposits" on public.deposit_requests;
drop policy if exists "public insert deposits" on public.deposit_requests;
drop policy if exists "public update deposits" on public.deposit_requests;
drop policy if exists "public read withdrawals" on public.withdrawal_requests;
drop policy if exists "public insert withdrawals" on public.withdrawal_requests;
drop policy if exists "public update withdrawals" on public.withdrawal_requests;

drop policy if exists "public read wallet ledger" on public.wallet_ledger;
drop policy if exists "public insert wallet ledger" on public.wallet_ledger;

drop policy if exists "public read subscription plans" on public.subscription_plans;
drop policy if exists "public insert subscription plans" on public.subscription_plans;
drop policy if exists "public update subscription plans" on public.subscription_plans;
drop policy if exists "public delete subscription plans" on public.subscription_plans;

drop policy if exists "public read kyc" on public.kyc_requests;
drop policy if exists "public insert kyc" on public.kyc_requests;
drop policy if exists "public update kyc" on public.kyc_requests;

drop policy if exists "public read admin signals" on public.admin_signals;
drop policy if exists "public insert admin signals" on public.admin_signals;

drop policy if exists "public read referrals" on public.referrals;
drop policy if exists "public insert referrals" on public.referrals;

-- Open policies for test build. Tighten these before real production.
create policy "public read profiles" on public.profiles for select using (true);
create policy "public insert profiles" on public.profiles for insert with check (true);
create policy "public update profiles" on public.profiles for update using (true);

create policy "public read trades" on public.trades for select using (true);
create policy "public insert trades" on public.trades for insert with check (true);

create policy "public read payments" on public.payment_requests for select using (true);
create policy "public insert payments" on public.payment_requests for insert with check (true);
create policy "public update payments" on public.payment_requests for update using (true);

create policy "public read deposits" on public.deposit_requests for select using (true);
create policy "public insert deposits" on public.deposit_requests for insert with check (true);
create policy "public update deposits" on public.deposit_requests for update using (true);

create policy "public read withdrawals" on public.withdrawal_requests for select using (true);
create policy "public insert withdrawals" on public.withdrawal_requests for insert with check (true);
create policy "public update withdrawals" on public.withdrawal_requests for update using (true);

create policy "public read wallet ledger" on public.wallet_ledger for select using (true);
create policy "public insert wallet ledger" on public.wallet_ledger for insert with check (true);

create policy "public read subscription plans" on public.subscription_plans for select using (true);
create policy "public insert subscription plans" on public.subscription_plans for insert with check (true);
create policy "public update subscription plans" on public.subscription_plans for update using (true);
create policy "public delete subscription plans" on public.subscription_plans for delete using (true);

create policy "public read kyc" on public.kyc_requests for select using (true);
create policy "public insert kyc" on public.kyc_requests for insert with check (true);
create policy "public update kyc" on public.kyc_requests for update using (true);

create policy "public read admin signals" on public.admin_signals for select using (true);
create policy "public insert admin signals" on public.admin_signals for insert with check (true);

create policy "public read referrals" on public.referrals for select using (true);
create policy "public insert referrals" on public.referrals for insert with check (true);


insert into public.subscription_plans (id, name, price, duration, signal_limit, features, active)
values
('free', 'Free', 0, 'Lifetime', 5, '["5 signals/day","Demo dashboard","Live prices"]'::jsonb, true),
('pro', 'Pro', 499, '30 days', 50, '["50 signals/day","Advanced AI indicator","Referral bonus tracking"]'::jsonb, true),
('elite', 'Elite', 999, '30 days', 999999, '["Unlimited signals UI","PnL analytics","Priority dashboard"]'::jsonb, true)
on conflict (id) do nothing;


-- wallet_ledger type examples:
-- DEPOSIT = approved deposit amount
-- WITHDRAWAL = approved withdrawal amount as negative value
-- TRADE_PNL = closed trade profit/loss, positive or negative
