-- Supabase Database Setup
-- Supabase Dashboard > SQL Editor > New Query > Paste > Run

create table if not exists public.profiles (
  id text primary key,
  created_at timestamp with time zone default now(),
  name text,
  email text unique,
  mobile text,
  role text default 'user',
  plan text default 'Free',
  referral_code text unique,
  referred_by text
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text references public.profiles(id),
  coin text,
  side text,
  amount numeric,
  entry_price numeric,
  current_price numeric,
  pnl numeric,
  status text default 'RUNNING'
);

create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_id text,
  plan text,
  name text,
  mobile text,
  txn text,
  screenshot_url text,
  status text default 'PENDING'
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  referral_code text,
  joined_user_email text,
  bonus numeric default 50,
  status text default 'JOINED'
);

alter table public.profiles enable row level security;
alter table public.trades enable row level security;
alter table public.payment_requests enable row level security;
alter table public.referrals enable row level security;

-- Basic public policies for test build. Tighten before production.
create policy "public read profiles" on public.profiles for select using (true);
create policy "public insert profiles" on public.profiles for insert with check (true);
create policy "public update profiles" on public.profiles for update using (true);

create policy "public read trades" on public.trades for select using (true);
create policy "public insert trades" on public.trades for insert with check (true);

create policy "public read payments" on public.payment_requests for select using (true);
create policy "public insert payments" on public.payment_requests for insert with check (true);
create policy "public update payments" on public.payment_requests for update using (true);

create policy "public read referrals" on public.referrals for select using (true);
create policy "public insert referrals" on public.referrals for insert with check (true);
